apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: pageperformancecacher
spec:
  schedule: "0 1 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: covidinventorycreator
            image: tbsacr.azurecr.io/covidinventorycreator:1.0.0
            imagePullPolicy: Always
          restartPolicy: OnFailure
          volumeMounts:
          - name: import
            mountPath: /app/data
        restartPolicy: OnFailure
        volumes:
        - azureFile:
          secretName: covid19-storage
          shareName: covid19-inv
          name: data
