apiVersion: batch/v1
kind: CronJob
metadata:
  name: covidinventorycreator
spec:
  schedule: "0 0 1-31/2 * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: covidinventorycreator
            image: tbsacr.azurecr.io/covidinventorycreator:1.0.0
            imagePullPolicy: Always
            volumeMounts:
            - name: data
              mountPath: /app/data
          volumes:
          - azureFile:
              secretName: covid19-storage
              shareName: covid19-inv
            name: data
          restartPolicy: OnFailure
          
        
          
